### ISSUE TITLE
Which tech

### ISSUE THREAD

**Issue by tyrsensei** [wtfcoderz/bigdata4all#1]
Need to investigate on which technologies to use :

- For database
- For API
- For backend
- For frontend

**Comment by WTFKr0** [comment]
- Database
I think we can start on a key/value NoSql DB, and we store raw data the client send
DB like Mongo/Redis
- API
I think this API should inject in DB and present REST API (json)
So node is the simplest today
GO is certainly better in perf and contenerizable
- Backend
What you put in backend ?
I think all must be playable by API, so the API is the backend, no ?
- Frontend
Don't know, js framework for sure
Angular/React/...

**Comment by tyrsensei** [comment]
> What you put in backend ?
> I think all must be playable by API, so the API is the backend, no ?

I was thinking of having an API for the provided service, and a backend (that can be an API as well) for the website. It would be only to keep separated the core of the project from the website. Indeed, the website back would be calling the service API.

We need to keep both separated for security reason as well I think.

For the front, an strong API oriented would be a good choice, but other criteria should be analyzed. I'm thinking of the graphic design part, each framework having its set of available components.
